applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'persona_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name= 'empleado_all'
    ),
    path(
        'listar-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name= 'empleados_admin'
    ),
    path(
        'lista-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path('lista-by-job/<job>/', views.ListByJobEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'detalle-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'  
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='success'
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path,re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from ckeditor.fields import RichTextField
from django.db import models
from applications.departamento.models import Departamento


# Create your models here.
class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleados'

    def __str__(self):
        return f'{str(self.pk)}-{self.habilidad}'


class Empleado(models.Model):
    # Modelo para tabla Empleado

    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField(
        'Nombre Completo',
        max_length=120,
        blank=True
    )
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidad = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural = 'Integrantes de la empresa'
        unique_together = ('first_name', 'last_name')

    def __str__(self):
        return f'{str(self.pk)}-{self.first_name}-{self.last_name}'

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidad',
        )
        widgets = {
            'habilidad': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  TemplateView,
                                  UpdateView,
                                  DeleteView)
# Models
from .models import Empleado
from django.urls import reverse_lazy
#forms
from .forms import EmpleadoForm
# Create your views here.
class InicioView(TemplateView):
    """Vista que carga la pagina de inicio"""
    template_name= 'inicio.html'


class ListaEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    ordering = 'first_name'
    paginate_by = 8
    context_object_name = 'all_empleados'
    model = Empleado


class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    ordering = 'first_name'
    paginate_by = 4
    context_object_name = 'all_empleados'

    def get_queryset(self):
        # sourcery skip: inline-immediately-returned-variable
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(full_name__icontains=palabra_clave)
        return lista

class ListByAreaEmpleado(ListView):
    """Lista empleados de un area"""
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        # sourcery skip: inline-immediately-returned-variable
        # Override
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(departamento__shor_name=area)
        return lista

class ListByJobEmpleado(ListView):
    template_name = 'persona/list_by_job.html'

    def get_queryset(self):
        # Override
        job = self.kwargs['job']
        return Empleado.objects.filter(job=job)


class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        return Empleado.objects.filter(first_name=palabra_clave)


class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        id_clave = int(self.request.GET.get('skills', ''))
        empleado = Empleado.objects.get(id=id_clave)
        return empleado.habilidad.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'persona/detail_empleado.html'

    def get_context_data(self, **kwargs):
        empleado = self.object
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = f'{empleado.first_name} {empleado.last_name}'
        return context


class SuccessView(TemplateView):
    template_name = 'persona/success.html'


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = 'persona/add.html'
    form_class = EmpleadoForm
    # fields = [
    #     'first_name',
    #     'last_name',    
    #     'job',
    #     'departamento',
    #     'habilidad',
    #     'avatar',
    # ]
    success_url = reverse_lazy('persona_app:empleado_all')

    def form_valid(self, form):
        # Logica del proceso
        empleado = form.save(commit=False)
        empleado.full_name = f'{empleado.first_name} {empleado.last_name}'
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = 'persona/update.html'
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidad'
    ]
    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('************POST************')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # Logica del proceso
        print('****************VALID*************')
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'persona/delete.html'
    success_url = reverse_lazy('persona_app:empleados_admin')

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        try:
            return super(EmpleadoDeleteView, self).form_valid(form='POST')
        except ProtectedError:
            self.object = self.get_object()
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)

    def form_valid(self, form):
        empleado = self.object
        print(empleado.first_name)
        empleado.save()
        return super(EmpleadoDeleteView, self).form_valid(form)

templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
    Crear empleado
{% endblock title %}
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}

            <div class="medium-6 cell">
                <label>Nombre:
                  {{ form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellido:
                  {{ form.last_name}}
                </label>
            </div><div class="medium-6 cell">
                <label>Trabajo:
                  {{ form.job}}
                </label>
            </div><div class="medium-6 cell">
                <label>Departamento:
                  {{ form.departamento}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades:
                  {{ form.habilidad}}
                </label>
            </div>
            <div class="medium-12 cell">
              <label>Foto:
                {{ form.avatar}}
              </label>
          </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>
        </form>    
    </div>
</div>



{% endblock content %}
    

templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<form method="GET">{% csrf_token %}
  <input type="text" id="kword" name="kword" placeholder="ingrese nombre aqui">
  <button type="submit">buscar</button>
</form>

<h3>Lista empleados</h3>

<ul>
  {% for e in empleados %}
    <li>{{ e }}</li>
  {% endfor %}
</ul>

templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar empleado
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="Cell">Eliminar empleado: {{object.full_name}}</h1>

        <form class="cell" method="POST">{% csrf_token %}

            <div class="callout warning">
                <h5>¿Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>

        </form>
    </div>
</div>
    
{% endblock content %}
    

templates/persona/detail_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Detalles Empleado: {{titulo}}</h1>
        <div class="cell">
            <table style="border: 2px solid #00BFFF">
                <tr>
                    <th style="border:1px solid #00BFFF; text-align: center;">Nombres</th>
                    <td style="border:1px solid #00BFFF; text-align: center;">{{ empleado.first_name }}</td>
                </tr>
                <tr>
                    <th style="border:1px solid #00BFFF; text-align: center;">Apellidos</th>
                    <td style="border:1px solid #00BFFF; text-align: center;">{{ empleado.last_name }}</td>
                </tr>
                <tr>
                    <th style="border:1px solid #00BFFF; text-align: center;">Trabajo</th>
                    <td style="border:1px solid #00BFFF; text-align: center;">{{ empleado.get_job_display }}</td>
                </tr>
                <tr>
                    <th style="border:1px solid #00BFFF; text-align: center;">Departamento</th>
                    <td style="border:1px solid #00BFFF; text-align: center;">{{ empleado.departamento.shor_name }}</td>
                </tr>
                <tr>
                    <th style="border:1px solid #00BFFF; text-align: center;">Habilidades</th>
                    <td style="border:1px solid #00BFFF; text-align: center;">
                        <ul class="vertical menu"> 
                            {% for h in empleado.habilidad.all %}
                                <li>{{ h.habilidad }}</li>
                            {% endfor %}   
                        </ul>
                    </td>
                </tr>
                <tr>
                    <th style="border:1px solid #00BFFF; text-align: center;">Foto</th>

                    <td style="border:1px solid #00BFFF; text-align: center;">
                        <div class="media-object-section">
                            <div class="thumbnail">
                                {% if empleado.avatar %}
                                    <img src='{{ empleado.avatar.url }}' width="350" height="350">
                                {% else %}
                                    <img src="{% static 'img/desco.jpg' %}" width="350" height="350">
                                {% endif %}
                            </div>
                        </div>
                    </td>

                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock content %}
    

templates/persona/habilidades.html
<h1>Habilidades Empleado</h1>
<form method="GET">{% csrf_token %}
  <input type="text" id="skills" name="skills" placeholder="ingrese el ID aqui">
  <button type="submit">buscar</button>
</form>

<ul>
    {% for h in habilidades %}
        <li>{{ h }}</li>
    {% endfor %}
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="submit success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for e in all_empleados %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">VER</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">  
            {% if  is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">   
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% else %}
                    <li class="pagination-previous disabled">Atras</li>      
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                    {% if pagina == page_obj.number %} 
                    <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li> 
                    {% else %}
                    <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>  
                    {% endif %} 
                    {% endfor %}
                    
                    
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</a>
                    </li>
                    {% else %}
                    <li class="pagination-previous disabled">Siguiente</li>     
                    {% endif %}
                        
                    
                </ul>
              </nav>   
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}
    

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    lista empleados por departamento
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Empleados por area:</h1>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="200">ID</th>
                            <th>NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCION</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for e in empleados %}
                        <tr>
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">VER</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}
    

<h1>Es lista empleados por departamento</h1>

<ul>
    {% for e in object_list %}
        <li>{{ e }}</li>
    {% endfor %}
</ul>

templates/persona/list_by_job.html
<h1>Es lista empleados por trabajo</h1>

<ul>
    {% for j in object_list %}
        <li>{{ j }}</li>
    {% endfor %}

</ul>

templates/persona/lista_empleados.html
{% extends 'base.html' %}


{% block title %}
    Administrar empleados
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for e in all_empleados %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">  
            {% if  is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">   
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% else %}
                    <li class="pagination-previous disabled">Atras</li>      
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                    {% if pagina == page_obj.number %} 
                    <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li> 
                    {% else %}
                    <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>  
                    {% endif %} 
                    {% endfor %}
                    
                    
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</a>
                    </li>
                    {% else %}
                    <li class="pagination-previous disabled">Siguiente</li>     
                    {% endif %}
                        
                    
                </ul>
              </nav>   
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}
    

templates/persona/success.html
<h1>Se ha agregado correctamente</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
    Editar empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombre:
                        {{ form.first_name }}
                    </label>
                  </div>
                  <div class="cell large-6">
                    <label>Apellido:
                        {{ form.last_name }}
                    </label>
                  </div>
                  <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job }}
                    </label>
                  </div>
                  <div class="cell large-6">
                    <label>Departamento:
                        {{ form.departamento }}
                    </label>
                  </div>
                  <div class="cell large-6">
                    <label>Habilidades:
                        {{ form.habilidad }}
                    </label>
                  </div>
                  <div class="cell">
                    <button class="submit success button">Guardar</button>
                  </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}