applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'departamento_app'

urlpatterns = [
    path(
        "departamento-lista/",
        views.DepartamentoListView.as_view(),
        name="departamento_list",
    ),
    path(
        "new-departamento/",
        views.NewDepartamentoView.as_view(),
        name="nuevo_departamento",
    ),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'persona_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name= 'empleado_all'
    ),
    path(
        'listar-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name= 'empleados_admin'
    ),
    path(
        'lista-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path('lista-by-job/<job>/', views.ListByJobEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'detalle-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'  
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='success'
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path,re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models


# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50, blank=True)
    shor_name = models.CharField('Nombre corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la empresa'
        unique_together = ('name', 'shor_name')

    def __str__(self):
        return f'{str(self.pk)}-{self.shor_name}'

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)
    

applications/departamento/views.py
from django.views.generic import (ListView)
from django.views.generic.edit import (FormView)

from applications.persona.models import Empleado
from .models import Departamento

from .forms import NewDepartamentoForm  
# Create your views here.


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = 'departamentos'


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('*****ESTAMOS AAAA*******')

        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            full_name=f'{nombre} {apellido}',
            job='1',
            departamento=depa
        )

        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.shor_name}}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a>
                            </td>
                        </tr>   
                        {% endfor %}  
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
    Registrar departamento
{% endblock title %} 
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registro de departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}

            <h3 class="cell">Empleado del departamento</h3>
            <div class="medium-6 cell">
                <label>Hombre:
                  {{ form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellido:
                  {{ form.apellido}}
                </label>
            </div>
            <h3 class="cell">Nuevo Departamento</h3>
            <div class="medium-6 cell">
                <label>Departamento:
                  {{ form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>shorname:
                  {{ form.shorname}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}
    

<h1>Registrar nuevo Departamento</h1>

<form method="POST">{% csrf_token %}
    <h3>Datos empleado</h3>
    <p>
        {{form.nombre}}
    </p>
    <p>
        {{form.apellido}}
    </p>
    <h3>Datos departamento</h3>
    <p>
        {{form.departamento}}
    </p>
    <p>
        {{form.shorname}}
    </p>
    <button type="submit">Guardar</button>
</form>